---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

-   Services:
    - Todo API:
        container: todoapi
        icon: si-dotnet
        href: http://100.90.164.103:5000/
        description: ASP.NET Core Todo API (Tailscale)

    - PostgreSQL:
        container: todo-db
        icon: si-postgresql
        description: PostgreSQL database for Todo App


    - Todo App:
        href: https://server.tail0e60ba.ts.net/todoapp/
        container: todoapi
        icon: si-ticktick
    - Minecraft:
        container: minecraft-server
        icon: si-minecraft
        description: Minecraft server
